name: Build, Test, and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: false
          prerelease: true

      - name: Ensure lock file is up to date
        run: |
            pdm lock --check

      - name: Install dependencies
        run: |
          pdm sync -dG dev

      - name: Lint
        run: |
          pdm run lint

      - name: Run tests
        run: |
          pdm run test
