name: Release

on:
  pull_request:
    branches-ignore:
      - 'master'
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  release-to-pypi:
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.12
        cache: true
        prerelease: true

    - name: Build package
      run: |
        pdm build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
